module.exports={
    baseUrl:'https://patient-dev.geton-institut.com/en',
    isHeadless:true,
    slowMo:0,
    isDevtools:false,
    launchTimeout:20000,
    waitingTimeout:20000,
    viewRepotWidth:1200,
    viewRepotHeight:1000
}